### ISSUE TITLE
Age filtering

### ISSUE THREAD

**Issue by kellys37** [dyisaev/ENIGMA#13]
No age filtering for adult and adolescent tests in MDD DTI model.

**Comment by dyisaev** [comment]
Fixed today.

The problem was: NewRegressors column and the way it was processied implied that each statement introduces a new variable. In the current case, in NewRegressors column a new variable was first introduced, and in the next 2 statements it's values were re-assigned. 

I edited the code so that re-assignment is now possible too.

 I'd suggest you to test the amount of AO21==1 and AO21==2 in the demographic variables, and compare it with the amount of lines with Age<22 and Age>=22 -- to be sure that reassignment works properly.

Thanks.
